#DOCKER BUILD THE API ONLY NOTHING REGARDING THE DB

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
#WORKDIR /APP ESTABLISHISHES WHICH DIRECTORY WE'RE WORKING IN
WORKDIR /app
#WE SPLIT DOTNET RESTORE AND DOTNET PUBLISH
#1. BECAUSE WE DON'T WANT TO DOWNLOAD ALL THE SAME PACKAGES AGAIN IF NOTHING CHANGES
#2. WE ONLY WANT TO DOWNLOAD THE CHANGES MADE EVERYWHERE ELSE
#DOTNET RESTORE DOWNLOADS ALL THIRD PARTY LIBRARIES IN .CSPROJ
#THE (.) AT THE END OF .csproj MEANS TO COPY IT INTO THE CURRENT WORKING DIRECTORY
COPY *.csproj .
RUN dotnet restore
#WE COPY ALL THE OTHER FILES AND COMPILE IT
COPY . .
#DOTNET PUSHLING -> COMPILES CODE INTO RUNNABLE PACKAGE
#-c RELEASE ->  OPTIMIZE FOR PRODUCTION
#-o /publish -> OUTPUT THE COMPILED FILES INTO A FOLDER CALLED /publish
#BASICALLY TRANSLATES ALL ENGLISH READABLE CODE INTO .dll (COMPUTER CODE)
RUN dotnet publish -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /publish . 
COPY --from=build /app/client ./client
CMD ["dotnet", "track-tasks.dll"]

#DIFFERENCE BETWEEN RUN AND CMD:
#RUN EXECUTES DURING THE BUILD, (BAKING INTO THE IMAGE)
#CMD EXECUTES WHEN THE CONTAINERS STARTS TO LAUNCH YOUR APP

#WHY WE HAVE 2 FROM LINES:
#WE NEED THE FULL OPERATING ENVIRONMENT OF SDK TO TURN SOURCE CODE INTO .dll
#THEORETICALLY WE CAN USE SDK TO RUN THE PROJECT...
#...BUT THE IMAGE CONTAINER WOULD BE A MUCH BIGGER SIZE
