version: '3.8'

services:
  api:
    build: .
    ports:
      - "5056:8080"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=tracktasks;Username=jimmyren;Password=postgres

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jimmyren
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tracktasks